# Generated by Django 3.2.7 on 2021-09-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='interest',
            field=models.CharField(max_length=100),
        ),
    ]
