# Generated by Django 3.2.7 on 2021-09-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBackend', '0003_auto_20210927_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
