# Generated by Django 3.2.7 on 2021-09-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBackend', '0005_alter_userdetail_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='email',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user_email',
            field=models.CharField(default='user_email', max_length=60),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='interest',
            field=models.CharField(max_length=100),
        ),
    ]
